services:
  db:
    image: mysql:8.0
    container_name: new-college-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - new-db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/new-init.sql

volumes:
  new-db_data:
