name: Testing

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - main


jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - "${MYSQL_PORT}:3306"
        options: >-
          --network=host
          --restart=always
        env:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      node-exporter:
        image: prom/node-exporter:latest
        ports:
          - 9100:9100
        options: >-
          --network=host
          --restart=always
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23.8.0

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm run test 